[project]
name = "rag-rbac-chatbot-01"
version = "0.1.0"
description = "Internal Chatbot with Role Based Access Control"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "chromadb",
    "fastapi[standard]>=0.115.12",
    "langgraph",
    "ollama",
    "openai",
    "pandas",
    "pyyaml",
    "qdrant-client",
    "sentence-transformers",
]

[project.optional-dependencies]
web = ["requests", "streamlit"]
dev = ["pytest"]
